store-before/config/routes.rb
Store::Application.routes.draw do
  root to: 'products#index'
  resources :products
end

store-before/app/models/product.rb
class Product < ActiveRecord::Base
end

store-before/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

store-before/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.order("name").page(params[:page]).per_page(10)
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(params[:product])
    if @product.save
      redirect_to @product, notice: "Successfully created product."
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update_attributes(params[:product])
      redirect_to @product, notice: "Successfully created product."
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_url, notice: "Successfully destroyed product."
  end
end

store-before/app/helpers/application_helper.rb
module ApplicationHelper
end

store-before/app/helpers/products_helper.rb
module ProductsHelper
end

store-before/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Store</title>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= yield %>
      <div class="clear"></div>
    </div>
  </body>
</html>

store-before/app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :released_at %><br />
    <%= f.date_select :released_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

store-before/app/views/products/_product.html.erb
<div class="product">
  <h2><%= link_to product.name, product %></h2>
  <div class="details">
    <%= number_to_currency(product.price) %> |
    Released <%= product.released_at.strftime("%B %e, %Y") %>
  </div>
</div>

store-before/app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

store-before/app/views/products/index.html.erb
<h1>Products</h1>

<div id="products">
  <%= render @products %>
</div>

<%= will_paginate @products %>

store-before/app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

store-before/app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @product.name %>
</p>

<p>
  <b>Price:</b>
  <%= @product.price %>
</p>

<p>
  <b>Released at:</b>
  <%= @product.released_at %>
</p>


<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>